### PR TITLE
Electron variant bugfixes and nativefier opts extension

### PR DESCRIPTION
**Pull request by trybik**
Two bugs caught when testing on clean Win machine and enable passing opts to nativefier (icon, init windows size etc).

### CODE REVIEW

**Comment by trybik** [comment]
Could you elaborate on what are you hinting at?

I've seen you have already this `if (!interactive())` check in template "server.app". This kills R session. I've just fixed this pending terminal issue which prevented app from re-opening, This was due to "\K" option of "CMD".

**Comment by Dripdrop12** [comment]
O Nice! That is what changing that flag does!?! If so, it was so much easier than what I was thinking...

**Comment by Dripdrop12** [comment]
I thought we'd need to create a custom JavaScript handler in Electron.

**Comment by trybik** [comment]
If that's the issue you meant (pending terminal session), than "\C" (execute and terminate, instead of "\K"  execute and cont.) worked for me on clean Win7. Didn't test it for Win10 (but I'm guessing CMD didn't change).

**Comment by Dripdrop12** [comment]
@trybik You fixed it! It worked out of the box for me. Very nice work 👍. I'll try to find a few people to validate it and then merge it into the master branch.

**Pull request merged**
